InvoiceManagerApplication/InvoiceManagerApplication/Controllers/InvoiceController.cs
using InvoiceManagerApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InvoiceManagerApplication.Controllers
{
    public class InvoiceController : Controller
    {
        private IInvoiceInbox _inbox;
        public InvoiceController(IInvoiceInbox inbox)
        {
            _inbox = inbox;
        }
        /// <summary>
        /// used to add a new invoice
        /// </summary>
        /// <returns></returns>
        public ActionResult AddInvoice()
        {
            return View("AddEditInvoices");
        }
        /// <summary>
        /// Used to edit an existing invoice
        /// </summary>
        /// <param name="invoiceID"></param>
        /// <returns></returns>
        public ActionResult EditInvoice(int invoiceID)
        {
            Invoice inv = _inbox.GetInvoice(invoiceID);
            return View("AddEditInvoices",inv);
        }
        /// <summary>
        /// Shows the review Page
        /// </summary>
        /// <returns></returns>
        public ActionResult ReviewInvoices()
        {
            HttpContext.Cache["INBOX"] = _inbox;
            IEnumerable<Invoice> unpaiedInvoices = _inbox.GetUnPaidInvoices();
            ViewBag.Total = _inbox.GetUnpaidTotal();
            return View("InvoiceReview",unpaiedInvoices);
        }
        /// <summary>
        /// used to process the Invoice forum input
        /// </summary>
        /// <param name="invoice"></param>
        /// <returns></returns>
        public ActionResult ProcessInvoice(Invoice invoice, string submit)
        {
            switch (submit)
            {
                //for submiting new invoices
                case "Submit Invoice":
                    _inbox.AddInvoice(invoice);
                    HttpContext.Cache["INBOX"] = _inbox;
                    return RedirectToAction("AccountMain", "UserAccounts");
                //for updating existing invoices
                case "Save Invoice":
                    _inbox.AddInvoice(invoice);
                    HttpContext.Cache["INBOX"] = _inbox;
                    return RedirectToAction("ReviewInvoices");
            }
            return null;
        }

    }
}

InvoiceManagerApplication/InvoiceManagerApplication/Controllers/UserAccountsController.cs
using InvoiceManagerApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InvoiceManagerApplication.Controllers
{
    public class UserAccountsController : Controller
    {

        private IUserManager _userManager;

        public UserAccountsController(IUserManager userManager)
        {
            _userManager = userManager;
        }
        /// <summary>
        /// Inital Action. Shows the Main Login Page
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View("Index");
        }
        /// <summary>
        /// Process the users login and will return to the login if the user fails
        /// </summary>
        /// <param name="UserName"></param>
        /// <param name="Password"></param>
        /// <param name="submit"></param>
        /// <returns></returns>
        public ActionResult LoginAttempt(string UserName, string Password, string submit)
        {
            //tracks if login was a success
            bool success = true;
            bool manager = false;
            // used to process login
            switch (submit)
            {
                //checks if they are a manager
                case "Manager Login":
                    if (!_userManager.ValidateManager(UserName,Password))
                    {
                        ViewBag.IsManager = false;
                        success = false;
                    }else
                    {
                        manager = true;
                    }
                    //no fall through in C# :(
                    goto case "User Login";
                //checks if the user entered a valid password
                case "User Login":
                    
                    if (!_userManager.Validate(UserName,Password))
                    {
                        ViewBag.Valid = false;
                        success = false;
                    }
                    break;          
            }
            //return them to login if they failed
            if (!success)
            {
                return View("Index");
            }else
            {
                //save their info to the session and proceed
                Session["UserName"] = UserName;
                Session["Manager"] = manager; 
                return View("AccountMain");
            }
        }
        public ActionResult AccountMain()
        {
            return View("AccountMain");
        }
    }
}

InvoiceManagerApplication/InvoiceManagerApplication/Views/UserAccounts/AccountMain.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AccountMain</title>
</head>
<body>
    <div>
        <h1>Welcome @Session["UserName"]!</h1><hr /><br />
        @using (Html.BeginForm("AddInvoice", "Invoice"))
        {
            <input type="submit" value="Add Invoice" />
        }
        @if ((bool)Session["Manager"])
        {
            using (Html.BeginForm("ReviewInvoices", "Invoice"))
            {
                <input type="submit" value="Review Invoice" />
            }
        }
    </div>
</body>
</html>

InvoiceManagerApplication/InvoiceManagerApplication/Views/UserAccounts/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
</head>
<body>
    <div>
        <h2>Please Log in</h2><hr /><br/>
        @if(ViewBag.IsManager != null && !ViewBag.IsManager)
        {
            //not a manager
            <h4><font color="red">You are not a manager!</font></h4>
        }else if(ViewBag.Valid != null && !ViewBag.Valid)
        {
            //invalid password
            <h4><font color="red">Invalid Password</font></h4>
        }
        @using (Html.BeginForm("LoginAttempt", "UserAccounts"))
        {
            <p>UserName: @Html.TextBox("UserName", "")<br /> Password: @Html.Password("Password","")</p><br />
            <input type="submit" value="User Login" name="submit"/> <input type="submit" value="Manager Login" name="submit"/>
        }
    </div>
</body>
</html>